### ISSUE TITLE
Schematics missing/not doing anything

### ISSUE THREAD

**Issue by hyenaheartbeats** [AceTheEldritchKing/art_of_forging#22]
I am playing on 1.19.2; I found a halberd schematic but placing it anywhere near a workbench does nothing. I also cannot find the crafting recipe for the katana schematic in  JEI.

**Comment by ambientNexus** [comment]
Tetra scrolls don't properly display in JEI due to it having issues recognizing nbt-dependent items, you have to click on the treatise that does show up to see the recipes for the craftable scrolls. Scrolls do show up properly in REI however. 

As for the halberd just to make sure, you are using a shovel/single-head tool as the base and not something else?

**Comment by hyenaheartbeats** [comment]
This works, thank you!
