### ISSUE TITLE
Difficult Accessibility of Treatise

### ISSUE THREAD

**Issue by ElectroAegis** [AceTheEldritchKing/art_of_forging#3]
These neat scrolls are extremely difficult to even locate, let alone to pinpoint the exact recipe for such thing as using the "@" designation shows nothing for the JEI and the scrolls are not accessible in the Creative menu.

**Comment by AceTheEldritchKing** [comment]
Hey there!
Right now we are working on a way to integrate the scrolls into a creative menu, however it will take some time for that to be done.
In the meantime, if you do @tetra and then click on the scroll item that appears, all of the crafting recipes will be shown. The reason why there's only one scroll in the JEI menu for Tetra is because all the scrolls share the same item. The factor that gives them each a unique schematic is through the use of NBT values. So it won't display all of the scrolls at once, unfortunately.
