### ISSUE TITLE
how do you forge the cruicble the intended way

### ISSUE THREAD

**Issue by OrionsExile** [AceTheEldritchKing/art_of_forging#31]

**Comment by AceTheEldritchKing** [comment]
Check JEI/REI for scroll recipes, some materials needed are either dropped from mobs, found in forge ruins, or crafted by the player.
JEI doesn't show all scrolls, so press on the only scroll item when you search @Tetra. If you are using REI, it will show all the scrolls. This is because all scrolls are the same item but with different NBT tags
